name: version

run-name: Update version

on:
  push:
    branches:
      - main

jobs:
  update_version:
    runs-on: [self-hosted, linux]
    name: Update version
    steps:
      - id: new_version
        uses: nomasystems/update-project-version@latest
        with:
          latest-tag: "true"
          tag-prefix: "v"