name: version

run-name: Update version

on:
  push:
    branches:
      - '**'

jobs:
  update_version:
    runs-on: ubuntu-latest
    name: Update version
    steps:
      - id: new_version
        uses: nomasystems/update-project-version@latest
        with:
          latest-tag: "true"
          tag-prefix: "v"
