name: version

run-name: Update version

on:
  push:
    branches:
      - '**'

jobs:
  update_version:
    runs-on: ubuntu-latest #[self-hosted, linux]
    name: Update version
    steps:
      - id: new_version
        uses: nomasystems/update-project-version@v1.0.0
        with:
          tag-prefix: "v"
